EXTRAS=
ifneq ($(EXTRAS),)
EXTRAS_CLEAN=$(strip $(EXTRAS):../../../source)
else
EXTRAS_CLEAN=../../../source
endif

.PHONY: all

all:
ifeq ($(OS),Windows_NT)
	cd jerryscript/targets/mbedos5 && pip install -r tools/requirements.txt && cmd //C del source/js_encoded.cpp && cmd //C del source/pins.cpp && cmd //C del source/main.cpp && make BOARD=$(BOARD) EXTRA_SRC="$(EXTRAS_CLEAN)" EXTERN_BUILD_DIR=../../../out/$(BOARD) NO_JS=1
else
	cd jerryscript/targets/mbedos5 && pip install -r tools/requirements.txt && rm -f source/js_encoded.cpp && rm -f source/pins.cpp && rm -f source/main.cpp && make BOARD=$(BOARD) EXTRA_SRC="$(EXTRAS_CLEAN)" EXTERN_BUILD_DIR=../../../out/$(BOARD) NO_JS=1
endif
